<a href="https://colab.research.google.com/github/Viktory4121/diploma/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import xlrd
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# Сброс ограничений на количество выводимых рядов
pd.set_option('display.max_rows', None)
# Сброс ограничений на число столбцов
pd.set_option('display.max_columns', None)
# Сброс ограничений на количество символов в записи
pd.set_option('display.max_colwidth', None)

In [4]:
uploaded = files.upload()

Saving ConvertedTable.xlsx to ConvertedTable (1).xlsx


In [8]:
data = pd.read_excel(uploaded['ConvertedTable (1).xlsx'])
data

Возраст  Пол  ВУЗ  Курс  Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Q11  \
0         20    0    1     3   6   6   6   8   5   5   3   3   7    2    2   
1         20    1    1     3  10  10   5   0   0   0   5   4   0    0    0   
2         20    0    1     3   1   1   0   0   1   0   4  10   4   10    8   
3         20    1    1     3   5   5   4   4   4   4   4   5   4    8    8   
4         20    1    2     3   0   0   5   0   3   4   0   7   0    5   10   
5         20    0    1     3   5   6   4   1   1   1   3   5   6    8    7   
6         20    1   10     3   7   7   5   2   1   1   8   5   0    3    0   
7         22    1    2     3   6   6   9   5   2   2   2   0   8   10   10   
8         19    1   10     2   8  10   5   5  10   5   1   2   5   10    6   
9         19    0   10     2   5   5   6   2   1   1   3   4   2    2    2   
10        20    1    2     3   9   7   1   0   0   1   1   1   1    3    1   
11        19    0    1     3   3   3   4   0   0   2   3   4   2    6    3   
12        20    1    3     2   8   9   1   1   2   5   1  10   2    1    2   
13        23    1    3     2   4   3   2   2   3   2   2   6   3    8    5   
14        21    0    2     3  10  10  10  10  10  10  10  10  10   10   10   
15        20    1    2     3   0   0   0   0   0   0   0   0   0    5    6   
16        23    0    1     3   0   0   0   5   5   3   0   8   4    0    0   
17        19    1    2     3   0   0   0   0   0   0   0   3   0    5    5   
18        19    1    2     3   7   8   0   2   4   7   4  10   3    7    6   
19        20    0    1     3   3   1   1   5   3   2   9   7   0   10    9   
20        21    0    1     3   5   8   3   3   3   3   3   9   4    6    5   
21        20    0    1     3   3   3   0   1   4   5   0  10   3    5    4   
22        21    1    1     3   3   8   1   9  10  10   9   8   2   10   10   
23        20    1    1     3   1   0   1   0   0   0   1   1   0    1    1   
24        19    0    1     2   3   5   2   3   3   6   0  10   0    3    2   
25        19    1    0     2  10  10   1   6   8   2   8  10   2   10   10   
26        20    1   10     3   5   6   3   5   3   0   5   8   3    7    3   
27        21    1   10     4   7   6   5   6   7   5   4   7   7    8    6   
28        21    1   10     3   8   5   8   2   2   2   5   2   0    5    3   
29        24    1   10     0  10   8   7   6   6   5   4   7   2    4    3   
30        21    1   10     4   1   2   0   3   0   0   3  10   0   10    1   
31        20    1   10    -1   8   9  10  10  10  10  10  10   9    9   10   
32        20    1   10     3   8   1   3   5   5   2   3   1   2    7    1   
33        20    0    4     3   0   0   5   0   0   0   0   5   0    3    3   
34        20    1    4     3   0   3   0   0   0   3   5  10   3    3    5   
35        17    0    4     1   3   6   3   1   0   7   0   2   5    9    5   
36        19    1    4     1   5   9   4   3   0   0   0   0   0    7    7   
37        19    1    4     1   8   2   0   0   0   0   0   8   0    3    0   
38        18    1    4     1   4   2   4   5   7   5   3   7   2    8    5   
39        24    0    4     1   1   1   8   8   5   4   4  10   1    8    6   
40        19    1    4     1   4   5   0   0   0   0   0   9   9    7    6   
41        18    1    4     1   5   8   3   4   3   3   3   6   3    7    8   
42        18    1    4     1   6   5   3   3   5   4   6   5   8    4    5   
43        18    1    4     1   5   8   8   8   8   3   8  10   5    8    4   
44        18    1    4     1   9   2   0   1   4   2   0  10   5    5    4   
45        18    1    4     1   2   2   0   0   0   0   0   2   2    0    1   
46        18    1    4     1   1   1   0   0   0   0   5   2   0    8    5   
47        18    0    4     1  10  10   7  10  10   5  10  10   7    7    1   
48        19    1    4     1   6   6   0   0   7   7   3   6   0    2    5   
49        18    0    4     1   0   2   7   5   3   0   9  10   0    0    3   
50        18    1    4     

In [9]:
womenData = data[data['Пол'] == 1].copy()
menData = data[data['Пол'] == 0].copy()
#questionsData = data[data.columns[4:]].copy()

In [10]:
womenData.describe()

Возраст   Пол        ВУЗ       Курс        Q1         Q2         Q3  \
count  72.000000  72.0  72.000000  72.000000  72.00000  72.000000  72.000000   
mean   19.722222   1.0   4.513889   2.000000   5.12500   4.944444   2.194444   
std     1.576430   0.0   2.361624   1.138321   2.88726   3.112396   2.587287   
min    17.000000   1.0   0.000000  -1.000000   0.00000   0.000000   0.000000   
25%    19.000000   1.0   4.000000   1.000000   4.00000   2.000000   0.000000   
50%    20.000000   1.0   4.000000   2.000000   5.00000   5.000000   1.000000   
75%    20.000000   1.0   5.000000   3.000000   7.00000   7.250000   4.000000   
max    24.000000   1.0  10.000000   5.000000  10.00000  10.000000  10.000000   

              Q4         Q5         Q6       Q7         Q8         Q9  \
count  72.000000  72.000000  72.000000  72.0000  72.000000  72.000000   
mean    2.069444   2.402778   2.402778   3.2500   4.444444   2.208333   
std     2.574667   2.977189   2.487488   3.1922   3.808400   2.605182   
min     0.000000   0.000000   0.000000   0.0000   0.000000   0.000000   
25%     0.000000   0.000000   0.000000   0.0000   0.000000   0.000000   
50%     1.000000   1.000000   2.000000   2.0000   4.000000   2.000000   
75%     3.250000   4.000000   4.000000   5.0000   8.000000   3.000000   
max    10.000000  10.000000  10.000000  10.0000  10.000000   9.000000   

             Q10        Q11        Q12        Q13        Q14        Q15  \
count  72.000000  72.000000  72.000000  72.000000  72.000000  72.000000   
mean    4.361111   3.861111   2.555556   2.888889   4.069444   2.875000   
std     3.132319   3.036425   3.080556   2.943389   3.260201   2.742146   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     2.000000   1.000000   0.000000   0.000000   1.000000   1.000000   
50%     4.000000   4.000000   2.000000   2.000000   4.000000   2.000000   
75%     7.000000   6.000000   4.000000   5.000000   6.000000   4.000000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q16        Q17        Q18        Q19        Q20        Q21  \
count  72.000000  72.000000  72.000000  72.000000  72.000000  72.000000   
mean    4.361111   4.833333   4.166667   3.722222   4.513889   3.444444   
std     3.100684   2.863072   3.435523   2.854313   3.297430   2.978273   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     2.000000   2.750000   1.000000   1.000000   2.000000   0.000000   
50%     4.000000   5.000000   3.000000   3.000000   4.000000   3.000000   
75%     6.250000   7.000000   7.000000   6.000000   7.000000   5.000000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q22        Q23        Q24        Q25        Q26        Q27  \
count  72.000000  72.000000  72.000000  72.000000  72.000000  72.000000   
mean    4.930556   4.736111   3.583333   5.069444   2.875000   1.208333   
std     2.687092   3.166698   3.257710   3.096233   3.314235   2.245104   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     3.000000   2.000000   0.750000   3.000000   0.000000   0.000000   
50%     5.000000   4.000000   3.000000   5.000000   1.000000   0.000000   
75%     7.000000   7.000000   5.000000   7.250000   5.000000   2.000000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q28        Q29        Q30        Q31        Q32        Q33  \
count  72.000000  72.000000  72.000000  72.000000  72.000000  72.000000   
mean    2.402778   5.041667   4.527778   3.638889   3.583333   1.444444   
std     2.811745   2.971401   3.071781   3.674448   3.304926   2.396529   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     0.000000   3.000000   2.000000   0.000000   1.000000   0.000000   
50%     1.000000   5.000000   5.000000   3.000000   3.000000   0.000000   
75%     4.250000   7.000000   7.000000   6.250000   5.000000   2.000000   
ma

In [11]:
menData.describe()

Возраст   Пол        ВУЗ       Курс         Q1         Q2         Q3  \
count  34.000000  34.0  34.000000  34.000000  34.000000  34.000000  34.000000   
mean   20.294118   0.0   3.588235   2.235294   4.294118   4.676471   3.147059   
std     1.817914   0.0   1.940285   1.182161   2.907977   2.971793   2.720654   
min    17.000000   0.0   1.000000   0.000000   0.000000   0.000000   0.000000   
25%    19.250000   0.0   1.250000   1.000000   3.000000   2.000000   1.000000   
50%    20.000000   0.0   4.000000   3.000000   4.500000   5.000000   3.000000   
75%    21.000000   0.0   5.000000   3.000000   6.000000   6.000000   5.000000   
max    25.000000   0.0  10.000000   5.000000  10.000000  10.000000  10.000000   

              Q4         Q5         Q6         Q7         Q8         Q9  \
count  34.000000  34.000000  34.000000  34.000000  34.000000  34.000000   
mean    2.941176   2.647059   2.705882   2.588235   5.970588   2.823529   
std     3.044530   2.794826   2.528976   3.036322   3.672051   2.633935   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     0.000000   0.000000   0.250000   0.000000   3.000000   0.000000   
50%     2.000000   2.500000   2.000000   2.500000   5.000000   2.000000   
75%     5.000000   4.000000   4.750000   3.750000  10.000000   5.000000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q10        Q11        Q12        Q13        Q14        Q15  \
count  34.000000  34.000000  34.000000  34.000000  34.000000  34.000000   
mean    4.558824   3.970588   2.882353   3.029412   4.323529   2.588235   
std     3.448242   2.865524   3.319042   3.089428   3.042334   2.893228   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     2.000000   2.000000   0.000000   0.250000   2.000000   0.000000   
50%     3.500000   3.000000   2.000000   2.000000   4.000000   2.000000   
75%     7.750000   5.000000   5.000000   5.000000   7.000000   3.000000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q16        Q17        Q18        Q19        Q20        Q21  \
count  34.000000  34.000000  34.000000  34.000000  34.000000  34.000000   
mean    4.205882   3.970588   4.000000   4.411765   4.470588   3.382353   
std     3.207750   2.917921   2.849774   2.808188   3.202606   3.330435   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     2.000000   2.000000   2.000000   2.000000   2.000000   1.000000   
50%     3.500000   3.500000   3.000000   5.000000   4.000000   2.500000   
75%     6.500000   5.750000   6.000000   6.000000   6.000000   4.750000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q22        Q23        Q24        Q25        Q26        Q27  \
count  34.000000  34.000000  34.000000  34.000000  34.000000  34.000000   
mean    4.882353   4.529412   3.588235   4.647059   2.911765   2.205882   
std     2.590948   3.323336   2.986004   3.642197   3.360805   2.771931   
min     1.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     3.000000   2.000000   1.250000   1.250000   0.000000   0.000000   
50%     4.500000   4.000000   3.000000   5.000000   2.000000   1.000000   
75%     6.750000   7.000000   5.000000   7.000000   5.750000   4.000000   
max    10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   

             Q28        Q29        Q30        Q31        Q32        Q33  \
count  34.000000  34.000000  34.000000  34.000000  34.000000  34.000000   
mean    3.029412   5.294118   4.323529   4.441176   4.294118   1.529412   
std     2.757747   3.195920   3.052278   3.341123   3.242982   2.048433   
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
25%     1.000000   3.250000   2.000000   1.250000   2.000000   0.000000   
50%     2.500000   5.000000   5.000000   5.000000   4.000000   0.500000   
75%     5.000000   8.000000   6.750000   6.750000 

In [5]:
#метод главных компонент (без учителя, показывается как метод кластеризации)

#from sklearn.decomposition import PCA  # 1. Choose the model class
#model = PCA(n_components=2)            # 2. Instantiate the model with hyperparameters
#model.fit(womenData)                      # 3. Fit to data. Notice y is not specified!
#X_2D = model.transform(womenData)         # 4. Transform the data to two dimensions


#GMM

In [49]:
#смесь Гауссовых распределений (Gaussian mixture model, GMM)
from sklearn.mixture import GaussianMixture as GMM
modelGMM = GMM(n_components=4, covariance_type='spherical')

In [55]:
#обучение только по женщинам
womenGMM = modelGMM.fit(womenData[womenData.columns[4:]].T)
womenY_GMM = womenGMM.predict(womenData[womenData.columns[4:]].T)
womenY_GMM

array([0, 0, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,
       0, 0, 2, 0, 1, 3, 0, 0, 0, 3, 1, 0, 3, 3, 0, 3, 3, 3, 2, 1, 1, 3,
       3, 1, 3, 2, 2, 2, 1, 0])

In [56]:
#обучение только по мужчинам
menGMM = modelGMM.fit(menData[menData.columns[4:]].T)
menY_GMM = menGMM.predict(menData[menData.columns[4:]].T)
menY_GMM

array([2, 2, 3, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 1, 0, 1,
       1, 0, 1, 3, 3, 3, 2, 3, 3, 1, 0, 1, 3, 3, 1, 3, 3, 3, 3, 0, 0, 3,
       3, 0, 3, 1, 1, 3, 0, 3])

In [57]:
sumGMM = 0
indexBadSimilarity = []
for i in range(len(data.columns[4:])):
  if(womenY_GMM[i] == 0 and menY_GMM[i] == 2 or
     womenY_GMM[i] == 1 and menY_GMM[i] == 0 or
     womenY_GMM[i] == 2 and menY_GMM[i] == 1 or
     womenY_GMM[i] == 3 and menY_GMM[i] == 3 #or
     #womenY_GMM[i] == 4 and menY_GMM[i] == 3
     ):
    sumGMM += 1
  else:
    indexBadSimilarity.append(i + 1)

print(sumGMM, sumGMM/len(data.columns[4:]))
print(indexBadSimilarity)

30 0.5769230769230769
[3, 7, 8, 13, 15, 18, 19, 20, 21, 22, 23, 24, 26, 27, 30, 31, 32, 34, 37, 41, 50, 52]


In [ ]:
#2 - diag:
#42 0.8076923076923077
#[10, 14, 16, 18, 19, 20, 32, 39, 49, 50]

#3 spherical:
#43 0.8269230769230769
#[8, 12, 13, 19, 31, 35, 38, 40, 52]

#Kmeans


In [45]:
#метод кластеризации к-средних
from sklearn.cluster import KMeans
modelKmeans = KMeans(n_clusters=3)

In [52]:
#обучение только по женщинам
womenKmeans = modelKmeans.fit(womenData[womenData.columns[4:]].T)
womenY_Kmeans = womenKmeans.predict(womenData[womenData.columns[4:]].T)
womenY_Kmeans

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 2, 1, 1, 0, 2, 1, 0, 2, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 2], dtype=int32)

In [53]:
#обучение только по мужчинам
menKmeans = modelKmeans.fit(menData[menData.columns[4:]].T)
menY_Kmeans = menKmeans.predict(menData[menData.columns[4:]].T)
menY_Kmeans

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 2, 1, 1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0], dtype=int32)

In [10]:
#pd.DataFrame(np.matrix([womenY_Kmeans, menY_Kmeans]).T)

In [54]:
sumKmeans = 0
indexBadSimilarity = []
for i in range(len(data.columns[4:])):
  if(womenY_Kmeans[i] == 1 and menY_Kmeans[i] == 1 or
     womenY_Kmeans[i] == 0 and menY_Kmeans[i] == 0 or
     womenY_Kmeans[i] == 2 and menY_Kmeans[i] == 2 #or
     #womenY_Kmeans[i] == 4 and menY_Kmeans[i] == 5 or
     #womenY_Kmeans[i] == 5 and menY_Kmeans[i] == 5 or
     #womenY_Kmeans[i] == 1 and menY_Kmeans[i] == 1
     ):
    sumKmeans += 1
  else:
    indexBadSimilarity.append(i + 1)
print(sumKmeans, sumKmeans/len(data.columns[4:]))
print(indexBadSimilarity)

48 0.9230769230769231
[12, 13, 40, 52]


#Новый метод

#Метрики