<a href="https://colab.research.google.com/github/Viktory4121/diploma/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from google.colab import files
import xlrd
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
uploaded = files.upload()

Saving ConvertedTable.xlsx to ConvertedTable.xlsx


In [ ]:
data = pd.read_excel(uploaded['ConvertedTable.xlsx'])
data

Возраст  Пол  Учебное заведение  Курс  Q1  Q2  Q3  Q4  Q5  Q6  ...  Q43  \
0         20    0                  1     3   6   6   6   8   5   5  ...    8   
1         20    1                  1     3  10  10   5   0   0   0  ...    0   
2         20    0                  1     3   1   1   0   0   1   0  ...    0   
3         20    1                  1     3   5   5   4   4   4   4  ...    0   
4         20    1                  2     3   0   0   5   0   3   4  ...    0   
..       ...  ...                ...   ...  ..  ..  ..  ..  ..  ..  ...  ...   
101       24    1                  5     0   0   8   0   0   0   0  ...    0   
102       23    0                  5     0   3   1   1   1   3   3  ...    0   
103       24    1                  5     0   0   8   0   0   0   0  ...    0   
104       24    1                  5     0   0   8   0   0   0   0  ...    0   
105       20    1                  5     3   4   4   1   1   1   1  ...    0   

     Q44  Q45  Q46  Q47  Q48  Q49  Q50  Q51  Q52  
0     10   10    7    8   10    8   10    2    2  
1      0    2    0    0    0    0    0    1    0  
2      2   10    0   10   10   10   10    4    0  
3      3    5    5    5    3    5    5    0    1  
4      0    5    0    4    5    0    9    0    1  
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  
101    0    0    0    0    0    0    0    0    0  
102    0    0    0    0    4    0    0    0    0  
103    0    0    0    0    0    0    0    0    0  
104    0    0    0    0    0    0    0    0    0  
105    0    3    0    0    5    0    1    0    1  

[106 rows x 56 columns]

In [30]:
womenData = data[data['Пол'] == 1].copy()
menData = data[data['Пол'] == 0].copy()
#questionsData = data[data.columns[4:]].copy()

In [27]:
#метод главных компонент (без учителя, показывается как метод кластеризации)

from sklearn.decomposition import PCA  # 1. Choose the model class
model = PCA(n_components=2)            # 2. Instantiate the model with hyperparameters
model.fit(womenData)                      # 3. Fit to data. Notice y is not specified!
X_2D = model.transform(womenData)         # 4. Transform the data to two dimensions


#GMM

In [39]:
#смесь Гауссовых распределений (Gaussian mixture model, GMM)
from sklearn.mixture import GaussianMixture as GMM
modelGMM = GMM(n_components=3, covariance_type='full')

In [40]:
#обучение только по женщинам
womenGMM = modelGMM.fit(womenData[womenData.columns[4:]].T)
womenY_GMM = womenGMM.predict(womenData[womenData.columns[4:]].T)
womenY_GMM

array([1, 1, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 2, 2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2,
       1, 2, 1, 1, 1, 1, 2, 2])

In [41]:
#обучение только по мужчинам
menGMM = modelGMM.fit(menData[menData.columns[4:]].T)
menY_GMM = menGMM.predict(menData[menData.columns[4:]].T)
menY_GMM

array([2, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2,
       2, 0, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1,
       2, 1, 2, 2, 2, 2, 1, 1])

#Kmeans


In [42]:
#метод кластеризации к-средних
from sklearn.cluster import KMeans
modelKmeans = KMeans(n_clusters=3)

In [43]:
#обучение только по женщинам
womenKmeans = modelKmeans.fit(womenData[womenData.columns[4:]].T)
womenY_Kmeans = womenKmeans.predict(womenData[womenData.columns[4:]].T)
womenY_Kmeans

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([1, 1, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 1, 2, 2, 2, 2, 0, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0], dtype=int32)

In [46]:
#обучение только по мужчинам
menKmeans = modelKmeans.fit(menData[menData.columns[4:]].T)
menY_Kmeans = menKmeans.predict(menData[menData.columns[4:]].T)
menY_Kmeans

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 0, 1, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0,
       0, 2, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 2, 2, 1,
       1, 2, 1, 0, 1, 1, 2, 1], dtype=int32)