<a href="https://colab.research.google.com/github/Viktory4121/diploma/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import xlrd
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
uploaded = files.upload()

Saving ConvertedTable.xlsx to ConvertedTable.xlsx


In [3]:
data = pd.read_excel(uploaded['ConvertedTable.xlsx'])
data

Возраст  Пол  ВУЗ  Курс  Q1  Q2  Q3  Q4  Q5  Q6  ...  Q43  Q44  Q45  Q46  \
0         20    0    1     3   6   6   6   8   5   5  ...    8   10   10    7   
1         20    1    1     3  10  10   5   0   0   0  ...    0    0    2    0   
2         20    0    1     3   1   1   0   0   1   0  ...    0    2   10    0   
3         20    1    1     3   5   5   4   4   4   4  ...    0    3    5    5   
4         20    1    2     3   0   0   5   0   3   4  ...    0    0    5    0   
..       ...  ...  ...   ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...   
101       24    1    5     0   0   8   0   0   0   0  ...    0    0    0    0   
102       23    0    5     0   3   1   1   1   3   3  ...    0    0    0    0   
103       24    1    5     0   0   8   0   0   0   0  ...    0    0    0    0   
104       24    1    5     0   0   8   0   0   0   0  ...    0    0    0    0   
105       20    1    5     3   4   4   1   1   1   1  ...    0    0    3    0   

     Q47  Q48  Q49  Q50  Q51  Q52  
0      8   10    8   10    2    2  
1      0    0    0    0    1    0  
2     10   10   10   10    4    0  
3      5    3    5    5    0    1  
4      4    5    0    9    0    1  
..   ...  ...  ...  ...  ...  ...  
101    0    0    0    0    0    0  
102    0    4    0    0    0    0  
103    0    0    0    0    0    0  
104    0    0    0    0    0    0  
105    0    5    0    1    0    1  

[106 rows x 56 columns]

In [4]:
womenData = data[data['Пол'] == 1].copy()
menData = data[data['Пол'] == 0].copy()
#questionsData = data[data.columns[4:]].copy()

In [5]:
#метод главных компонент (без учителя, показывается как метод кластеризации)

from sklearn.decomposition import PCA  # 1. Choose the model class
model = PCA(n_components=2)            # 2. Instantiate the model with hyperparameters
model.fit(womenData)                      # 3. Fit to data. Notice y is not specified!
X_2D = model.transform(womenData)         # 4. Transform the data to two dimensions


#GMM

In [23]:
#смесь Гауссовых распределений (Gaussian mixture model, GMM)
from sklearn.mixture import GaussianMixture as GMM
modelGMM = GMM(n_components=2, covariance_type='full')

In [24]:
#обучение только по женщинам
womenGMM = modelGMM.fit(womenData[womenData.columns[4:]].T)
womenY_GMM = womenGMM.predict(womenData[womenData.columns[4:]].T)
womenY_GMM

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1])

In [25]:
#обучение только по мужчинам
menGMM = modelGMM.fit(menData[menData.columns[4:]].T)
menY_GMM = menGMM.predict(menData[menData.columns[4:]].T)
menY_GMM

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
sumGMM = 0
for i in range(len(data.columns[4:])):
  if(womenY_GMM[i] == 1 and menY_GMM[i] == 1 or
     womenY_GMM[i] == 0 and menY_GMM[i] == 4 or
     womenY_GMM[i] == 3 and menY_GMM[i] == 2 or
     womenY_GMM[i] == 2 and menY_GMM[i] == 1 or
     womenY_GMM[i] == 4 and menY_GMM[i] == 3):
    sumGMM += 1
print(sumGMM, sumGMM/len(data.columns[4:]))

31 0.5961538461538461


#Kmeans


In [ ]:
#метод кластеризации к-средних
from sklearn.cluster import KMeans
modelKmeans = KMeans(n_clusters=6)

In [ ]:
#обучение только по женщинам
womenKmeans = modelKmeans.fit(womenData[womenData.columns[4:]].T)
womenY_Kmeans = womenKmeans.predict(womenData[womenData.columns[4:]].T)
womenY_Kmeans

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 0, 1, 1, 1, 1, 2, 4, 1, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0, 3, 3, 0, 3, 3, 4, 4, 1, 1, 1,
       3, 1, 3, 4, 4, 4, 1, 5], dtype=int32)

In [ ]:
#обучение только по мужчинам
menKmeans = modelKmeans.fit(menData[menData.columns[4:]].T)
menY_Kmeans = menKmeans.predict(menData[menData.columns[4:]].T)
menY_Kmeans

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 0, 1, 1, 1, 1, 1, 4, 1, 2, 4, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 4,
       4, 2, 4, 3, 3, 3, 4, 0, 5, 5, 3, 2, 5, 5, 0, 5, 5, 5, 5, 1, 3, 5,
       5, 1, 5, 5, 5, 5, 1, 3], dtype=int32)

In [ ]:
pd.DataFrame(np.matrix([womenY_Kmeans, menY_Kmeans]).T)

0  1
0   0  0
1   0  0
2   1  1
3   1  1
4   1  1
5   1  1
6   2  1
7   4  4
8   1  1
9   0  2
10  0  4
11  2  2
12  2  2
13  0  2
14  2  1
15  0  2
16  0  2
17  0  2
18  0  2
19  0  2
20  0  2
21  0  4
22  0  4
23  2  2
24  0  4
25  2  3
26  1  3
27  1  3
28  0  4
29  2  0
30  2  5
31  2  5
32  1  3
33  0  2
34  3  5
35  3  5
36  0  0
37  3  5
38  3  5
39  4  5
40  4  5
41  1  1
42  1  3
43  1  5
44  3  5
45  1  1
46  3  5
47  4  5
48  4  5
49  4  5
50  1  1
51  5  3

In [ ]:
sumKmeans = 0
for i in range(len(data.columns[4:])):
  if(womenY_Kmeans[i] == 2 and menY_Kmeans[i] == 5 or
     womenY_Kmeans[i] == 0 and menY_Kmeans[i] == 2 or
     womenY_Kmeans[i] == 3 and menY_Kmeans[i] == 0 or
     womenY_Kmeans[i] == 4 and menY_Kmeans[i] == 5 or
     womenY_Kmeans[i] == 5 and menY_Kmeans[i] == 5 or
     womenY_Kmeans[i] == 1 and menY_Kmeans[i] == 1):
    sumKmeans += 1
print(sumKmeans, sumKmeans/len(data.columns[4:]))

24 0.46153846153846156


#Новый метод

#Метрики